Repository technojam/Ultimate_Algorithms_Repository, pull requests merged in 2020-10, with the labels that each got.

#58 Kahn's Algorithm added
  Basic Algorithms/Kahn's Algorithm.cpp
Labels: hacktoberfest

#83 Added class program for reversing and frequency count
  Strings/reverse_and_freq_count.cpp
Labels: hacktoberfest

#73 Created a directory for Graph and added Kruskal's code
  Graph/kruskalAlgorithm.cpp
Labels: hacktoberfest

#16 Basic Program: palindrome.cpp
  Strings/palindrome.cpp
Labels: hacktoberfest

#19 fixes:#15 Table of nth number
  Basic Algorithms/table_of_nth_number.cpp
Labels: hacktoberfest

#30 Added Russian Peasant Algorithm
  Basic Algorithms/RussianPeasant.cpp
Labels: hacktoberfest, invalid

#129 Create Prefix_Sum_Array.cpp
  Basic Algorithms/Prefix_Sum_Array.cpp
Labels: hacktoberfest

#27 fixes:#15 Check whether a number is prime or not
  Basic Algorithms/Number_is_prime_or_not.java
Labels: bug, hacktoberfest

#226 Fixes #225
  .DS_Store
  README.md
Labels: bug, hacktoberfest, hacktoberfest-approved

#267 In Basic Algorithm Added Sorting Algo.
  Basic Algorithms/BubbleSort.cpp
  Basic Algorithms/InsertionSort.cpp
  Basic Algorithms/README.md
  Basic Algorithms/SelectionSort .cpp
Labels: hacktoberfest

#86 Create GCD(Euclidean Algorithm)
  Basic Algorithms/GCD(Euclidean Algorithm)
Labels: hacktoberfest

#96 Added c++ code for checking Anagrams
  Strings/Check_For_Anagrams.cpp
Labels: hacktoberfest

#228 Fixes #225
  README.md
Labels: bug, hacktoberfest, hacktoberfest-accepted, hacktoberfest-approved

#171 algo: added linkedlist
  Data Structures/Linked List/SinglyLinkedList.cpp
Labels: hacktoberfest, hacktoberfest-approved

#217 Prims Algorithm for Minimum Spanning Tree
  Prims.cpp
  quickSort.cpp
Labels: hacktoberfest-accepted, hacktoberfest-approved

#182 clockwiseSpiral.cpp added
  2-D Arrays/clockwiseSpiral.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-approved

#290 Reverse words in a string program added
  Strings/reverse_words_of_string.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-approved

#269 Create LongestCommonPrefix.cpp
  Strings/LongestCommonPrefix.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-approved

#115 CombSort implementation in Java
  Basic Algorithms/CombSort.java
Labels: hacktoberfest, question

#164 Created Quick_Sort.cpp #82
  Basic Algorithms/Quick_Sort.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-approved, question

#292 Fixes technojam/Ultimate_Algorithms_Repository#218
  Basic Algorithms/CountSetBits.cpp
  Basic Algorithms/README.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-approved

#279 Added the code for problem Tower of hanoi #270
  Basic Algorithms/Tower of hanoi/README.md
  Basic Algorithms/Tower of hanoi/TowerOfHanoi.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-approved

#208 Added Z and Manachar's Algorithms
  Strings/Manchar.cpp
  Strings/Z algo.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-approved, question

#257 Fixes #256
  Dynamic Programming/box_stacking_DP.cpp
  Dynamic Programming/wildcard_matching_DP.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-approved

#216 Added Topographical Sort for a DAG
  Graphs/topologicalsort.cpp
  tree/Prims_minimum_spanning_tree.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-approved

#229 Extended Euclids Algo To Find Integer Coefficients And Multiplicative Modulo Inverse
  Basic Algorithms/extended _euclids_algo.cpp
  Basic Algorithms/multiplicative_modulo_inverse_using_extended_euclids_algo.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#241 Added Linked Lists Folder with 2 Questions
  LinkedLists/CountNodes.cpp
  LinkedLists/Max&MinOfLInkedList.cpp
  LinkedLists/Readme.md
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-approved

#296 Added Prim's algorithm
  Basic Algorithms/Prims_algorithm.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-approved

#38 Added code for KMP Algorithm
  Basic Algorithms/KnuthMorrisPratt.cpp
Labels: hacktoberfest, invalid

#319 Fixes #304
  Operating System/SRTF.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-approved

#330 Balanced Paranthesis
  Basic Algorithms/Balanced Parantheses.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest-approved
